mirrors = {'mirror1': {'url_prefix' : 'http://mirror1.com',
                         'metadata_path' : 'metadata',
                         'targets_path' : 'targets',
                         'confined_target_paths' : ['targets/target1.py',
                                                    'targets/target2.py']},
             'mirror2': {'url_prefix' : 'http://mirror2.com',
                         'metadata_path' : 'metadata',
                         'targets_path' : 'targets',
                         'confined_target_paths' : ['targets/target3.py',
                                                    'targets/target4.py']},
             'mirror3': {'url_prefix' : 'http://mirror3.com',
                         'metadata_path' : 'metadata',
                         'targets_path' : 'targets',
                         'confined_target_paths' : ['targets/target1.py',
                                                    'targets/target2.py']}}

